apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor
  namespace: istio-ingress
spec:
  hosts:
    - harbor.avgmax.team
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: harbor.harbor-system.svc.cluster.local
            port:
              number: 80
