installCRDs: true

imageAutomationController:
  enabled: false

imageReflectionController:
  enabled: false

notificationController:
  enabled: false

sourceController:
  enabled: true

kustomizeController:
  enabled: true

helmController:
  enabled: true

