resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits: {}

server:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

alertmanager:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

core:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

portal:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

registry:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

jobservice:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

loki:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

tempo:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}

mimir:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}