apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: n8n
  namespace: istio-ingress
spec:
  hosts:
    - n8n.avgmax.team # 여기는 Istio Gateway가 decription한 http url로 비교함
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      headers:
        request:
          add:
            X-Forwarded-Proto: "https"
      route:
        - destination:
            host: n8n.n8n.svc.cluster.local
            port:
              number: 5678