apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/policies
  # prune: false
  sourceRef:
    kind: GitRepository
    name: k8s-repo
